import { useState, useEffect, useRef } from 'react'
import { sections, metadata } from './data/content'
import Header from './components/Header'
import Sidebar from './components/Sidebar'
import ExecutiveSummary from './components/sections/ExecutiveSummary'
import InflectionPoint from './components/sections/InflectionPoint'
import RoleSection from './components/sections/RoleSection'
import EmergingRoles from './components/sections/EmergingRoles'
import SkillsImperative from './components/sections/SkillsImperative'
import Conclusion from './components/sections/Conclusion'
import './App.css'

const sectionComponents = {
  'executive-summary': ExecutiveSummary,
  'inflection-point': InflectionPoint,
  'software-engineers': RoleSection,
  'qa-testers': RoleSection,
  'security-engineers': RoleSection,
  'platform-engineers': RoleSection,
  'engineering-leaders': RoleSection,
  'product-managers': RoleSection,
  'data-ml-engineers': RoleSection,
  'emerging-roles': EmergingRoles,
  'skills-imperative': SkillsImperative,
  conclusion: Conclusion,
}

function App() {
  const [activeSection, setActiveSection] = useState('executive-summary')
  const [darkMode, setDarkMode] = useState(false)
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const observerRef = useRef(null)

  useEffect(() => {
    if (darkMode) {
      document.documentElement.setAttribute('data-theme', 'dark')
    } else {
      document.documentElement.removeAttribute('data-theme')
    }
  }, [darkMode])

  useEffect(() => {
    const callback = (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          setActiveSection(entry.target.id)
        }
      })
    }
    observerRef.current = new IntersectionObserver(callback, {
      rootMargin: '-20% 0px -60% 0px',
      threshold: 0,
    })
    sections.forEach(({ id }) => {
      const el = document.getElementById(id)
      if (el) observerRef.current.observe(el)
    })
    return () => observerRef.current?.disconnect()
  }, [])

  const scrollToSection = (id) => {
    const el = document.getElementById(id)
    if (el) {
      el.scrollIntoView({ behavior: 'smooth', block: 'start' })
      setSidebarOpen(false)
    }
  }

  return (
    <div className="app-wrapper">
      <Header
        metadata={metadata}
        darkMode={darkMode}
        onToggleDark={() => setDarkMode(!darkMode)}
        onMenuToggle={() => setSidebarOpen(!sidebarOpen)}
      />
      <div className="layout">
        <Sidebar
          sections={sections}
          active={activeSection}
          onNavigate={scrollToSection}
          isOpen={sidebarOpen}
          onClose={() => setSidebarOpen(false)}
        />
        <main className="main-content">
          {sections.map(({ id }) => {
            const Component = sectionComponents[id]
            return Component ? (
              <section key={id} id={id} className="content-section">
                <Component sectionId={id} />
              </section>
            ) : null
          })}
          <footer className="site-footer">
            <p>
              &copy; 2026 &mdash; <em>{metadata.title}</em> &mdash; Authored by {metadata.author}
            </p>
            <p className="footer-note">
              This document was generated by artificial intelligence as an analytical exercise.
              It represents the AI&rsquo;s informed perspective on workforce transformation, not institutional policy.
            </p>
          </footer>
        </main>
      </div>
    </div>
  )
}

export default App
